### ISSUE TITLE
GraphQL controllers

### ISSUE THREAD

**Issue by JurgenJocubeit** [gauravtiwari/relay-rails-blog#8]
Sorry about pestering you so often. I'm just wondering if you can explain the difference between the /graphql and /queries endpoints? The /graphql endpoint seems to be the registered endpoint for the client (clientRegistration.jsx)... just not sure where /queries endpoint is called from.

**Comment by gauravtiwari** [comment]
Hye @JurgenJocubeit , Sorry I forgot to remove this one. It's just one controller and endpoint. I have pushed an update on master, which removes the redundant controller and route resource. 

Thanks :)
