### ISSUE TITLE
Posts controller, routes and views

### ISSUE THREAD

**Issue by JurgenJocubeit** [gauravtiwari/relay-rails-blog#9]
I'm guessing the posts controller, routes and views on the rails side are left-over artifacts from the earlier react-rails version? Am I right, or am I confused?

**Comment by gauravtiwari** [comment]
Hye @JurgenJocubeit This is just for routes, without posts controller and show route, we can't navigate `/posts/:id` in rails, because the app is still standard rails app. If you using a separate client app, then you won't need these routes or controllers. Makes sense?

**Comment by gauravtiwari** [comment]
Just, pushed a small update to route and controller to make it more clear.
